---
- name: no root login
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    replace: 'PermitRootLogin no'
- name: reload sshd
  service:
    name: sshd
    state: reloaded
- name: prompt for password
  pause:
    prompt: "Enter password for hpc user"
    echo: false
  register: input
- name: set password
  set_fact:
    password: "{{ input.user_input }}"
  run_once: true
- name: add hpc user with sudo
  user:
    name: hpc
    shell: /bin/bash
    create_home: yes
    append: true
    groups: sudo
    password: "{{ password | password_hash('sha512') }}"
    update_password: on_create
  when: "'hpc_login' in group_names"