---
- name: No root login
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    replace: 'PermitRootLogin no'
- name: Reload sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded
- name: Prompt for password
  ansible.builtin.pause:
    prompt: "Enter password for hpc user"
    echo: false
  register: input
- name: Set password
  ansible.builtin.set_fact:
    password: "{{ input.user_input }}"
  run_once: true
- name: Add hpc user with sudo
  ansible.builtin.user:
    name: hpc
    shell: /bin/bash
    create_home: true
    append: true
    groups: sudo
    password: "{{ password | password_hash('sha512') }}"
    update_password: on_create
  when: "'hpc_login' in group_names"
