---
- name: set /etc/hosts and hostname
  include_tasks: set_hosts.yml

# - name: Set access control
#   ansible.builtin.include_tasks: access.yml

# - name: Set storage
#   ansible.builtin.include_tasks: storage.yml