---
- name: Set hostname
  ansible.builtin.include_tasks: hostname.yml

- name: Set access control
  ansible.builtin.include_tasks: access.yml

- name: Set storage
  ansible.builtin.include_tasks: storage.yml