---
- name: Get ansible facts for hostname
  ansible.builtin.setup:
    filter:
      - 'inventory_hostname'

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Get ansible facts for /etc/hosts
  ansible.builtin.setup:
    filter:
      - 'ansible_default_ipv4'
      - 'ansible_hostname'

- name: Replace /etc/hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
