---
- name: Delete vmstorage vg
  community.general.lvg:
    vg: vmstorage
    state: absent
- name: Extend root
  community.general.lvg:
    vg: system
    pvs: /dev/sda4
    pvresize: true
- name: Lvresize root to 128G
  community.general.lvol:
    vg: system
    lv: root
    size: 128G
    state: present
- name: Resize2fs
  community.general.filesystem:
    fstype: ext4
    dev: /dev/mapper/system-root
    resizefs: true
