---
- name: apt-get update
  apt:
    name: "*"
    state: latest
    update_cache: yes
- name: prepare for spack
  apt:
    pkg:
      - build-essential
      - ca-certificates
      - coreutils
      - curl
      - environment-modules
      - gfortran
      - git
      - gpg
      - lsb-release
      - python3
      - python3-distutils
      - python3-venv
      - unzip
      - zip
- name: get spack
  shell: "git clone -c feature.manyFiles=true https://github.com/spack/spack.git /opt/spack"
- name: set env for spack (create file with content)
  copy:
    dest: /etc/profile.d/spack.sh
    mode: '0644'
    content: 'source /opt/spack/share/spack/setup-env.sh'
