---
- name: Setup HPC Cluster for pp
  gather_facts: false
  become: true
  hosts: "{{ var_host }}"
  tasks:
    - name: install pp needed packages
      apt:
        pkg: 
          - linux-perf
          - gdb
          - ffmpeg
        state: latest
      when: "'hpc_compute' in group_names or 'hpc_login' in group_names"

    - name: set sysctl for perf
      sysctl:
        name: kernel.perf_event_paranoid
        value: 0
        state: present
        reload: true
      when: "'hpc_compute' in group_names or 'hpc_login' in group_names"

    - name: install tiv
      shell: |
        git clone https://github.com/stefanhaustein/TerminalImageViewer.git /tmp/tiv
        cd /tmp/tiv
        make
        sudo make install
      when: "'hpc_login' in group_names"
    