---
- name: Prepare for spack
  ansible.builtin.include_tasks: prepare.yml
  when: "'hpc_login' in group_names"

- name: Use first login node install spack to shared directory
  ansible.builtin.include_tasks: install.yml
  when: inventory_hostname == groups['hpc_login'][0]

- name: Set spack PATH for login nodes when ssh
  ansible.builtin.include_tasks: set_path.yml
  when: "'hpc_login' in group_names"
