---
- name: Do apt-get update
  ansible.builtin.apt:
    name: "*"
    state: present
    update_cache: true
- name: Prepare for spack
  ansible.builtin.apt:
    pkg:
      - build-essential
      - ca-certificates
      - coreutils
      - curl
      - environment-modules
      - gfortran
      - git
      - gpg
      - lsb-release
      - python3
      - python3-distutils
      - python3-venv
      - unzip
      - zip
