---
- name: apt-get update
  apt:
    name: "*"
    state: latest
    update_cache: yes
- name: prepare for spack
  apt:
    pkg:
      - build-essential
      - ca-certificates
      - coreutils
      - curl
      - environment-modules
      - gfortran
      - git
      - gpg
      - lsb-release
      - python3
      - python3-distutils
      - python3-venv
      - unzip
      - zip
