---
hpc_login: # login nodes
  hosts:
    hpc[056:060]:
hpc_slurmdbd: # slurmdbd nodes
  hosts:
    hpc051:
    hpc052:
hpc_db: # db node (no need to install slurm.deb)
  hosts:
    hpc052:
hpc_storage: # storage for nfs server
  hosts:
    hpc052:
hpc_control: # control nodes
  hosts:
    hpc051:
    hpc052:
hpc_compute: # compute nodes
  hosts:
    hpc[053:055]:

slurm_nodes: # nodes that need to install slurm.deb
  children:
    hpc_login:
    hpc_slurmdbd:
    hpc_control:
    hpc_compute:

hpc_test:
  children:
    hpc_login:
    hpc_slurmdbd:
    hpc_db:
    hpc_control:
    hpc_compute:
    hpc_storage:
