---
hpc_login: # login nodes
  hosts:
    192.168.1.[1:3]:
hpc_slurmdbd: # slurmdbd nodes
  hosts:
    192.168.1.[6:7]:
hpc_db: # db node (no need to install slurm.deb)
  hosts:
    192.168.1.8:
hpc_storage: # storage for nfs server
  hosts:
    192.168.1.9:
hpc_control: # control nodes
  hosts:
    192.168.1.[4:5]:
hpc_compute: # compute nodes
  hosts:
    192.168.1.[11:14]:

hpc_galera: # virtual IP for galera cluster
  hosts:
    192.168.1.21:

slurm_nodes: # nodes that need to install slurm.deb
  children:
    hpc_login:
    hpc_slurmdbd:
    hpc_control:
    hpc_compute:

hpc_test:
  children:
    hpc_login:
    hpc_slurmdbd:
    hpc_db:
    hpc_control:
    hpc_compute:
    hpc_storage:
    hpc_galera:
