---
- name: apt update
  apt:
    update_cache: yes

- name: install mpi and setup
  apt:
    pkg: 
    - openmpi-bin
    - openmpi-common
    - libopenmpi3
    - libopenmpi-dev

- name: reboot
  ansible.builtin.reboot: