---
- name: Apt update
  ansible.builtin.apt:
    update_cache: true

- name: Install mpi and setup
  ansible.builtin.apt:
    pkg:
      - openmpi-bin
      - openmpi-common
      - libopenmpi3
      - libopenmpi-dev

- name: Reboot
  ansible.builtin.reboot:
