---
- name: Do apt-get update
  ansible.builtin.apt:
    name: "*"
    state: present
    update_cache: true
- name: Build-dep for lmod
  ansible.builtin.apt:
    name: lmod
    state: build-dep
- name: Get lua ver. for lmod
  ansible.builtin.shell:
    cmd: "set -o pipefail && which lua | xargs realpath -e | xargs basename"
    executable: /bin/bash
  register: lua_ver
  changed_when: false
- name: Get dependency
  ansible.builtin.apt:
    pkg:
      - "lib{{ lua_ver.stdout }}-dev"
      - tcl-dev

- name: Download Lmod
  ansible.builtin.get_url:
    url: https://sourceforge.net/projects/lmod/files/Lmod-{{ lmod_version }}.tar.bz2/download
    dest: /tmp/lmod.tar.bz2
    mode: '0644'
- name: Extract
  ansible.builtin.unarchive:
    src: /tmp/lmod.tar.bz2
    dest: /tmp/
    remote_src: true
- name: Create directory for lmod
  ansible.builtin.file:
    path: /opt/apps
    mode: '0755'
    state: directory
- name: Configure location
  ansible.builtin.command:
    cmd: ./configure --prefix=/opt/apps
    chdir: /tmp/Lmod-{{ lmod_version }}/
  register: config_lmod
  changed_when: config_lmod.rc == 0
- name: Make install lmod
  community.general.make:
    chdir: /tmp/Lmod-{{ lmod_version }}/
    target: install
    # jobs: 12
- name: Create symlink for lmod env var
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: /opt/apps/lmod/lmod/init/profile, dest: /etc/profile.d/z00_lmod.sh }
    - { src: /opt/apps/lmod/lmod/init/cshrc, dest: /etc/profile.d/z00_lmod.csh }
    - { src: /opt/apps/lmod/lmod/init/profile.fish, dest: /etc/fish/conf.d/z00_lmod.fish }
