---
- name: install slurm.deb for compute nodes
  apt:
    deb=/tmp/{{ item }}
  with_items:
    - slurm-smd_{{ slurm_version }}-1_amd64.deb
    - slurm-smd-slurmd_{{ slurm_version }}-1_amd64.deb
    - slurm-smd-client_{{ slurm_version }}-1_amd64.deb
