---
- name: Install slurm.deb for compute nodes
  ansible.builtin.apt:
    deb: /tmp/{{ item }}
  with_items:
    - slurm-smd_{{ slurm_install_version }}-1_amd64.deb
    - slurm-smd-slurmd_{{ slurm_install_version }}-1_amd64.deb
    - slurm-smd-client_{{ slurm_install_version }}-1_amd64.deb
