---
- name: Install slurm.deb for control nodes
  ansible.builtin.apt:
    deb: /tmp/{{ item }}
  with_items:
    - slurm-smd_{{ slurm_install_version }}-1_amd64.deb
    - slurm-smd-slurmctld_{{ slurm_install_version }}-1_amd64.deb
    - slurm-smd-client_{{ slurm_install_version }}-1_amd64.deb
  when: not slurm_in_apt

- name: Install slurm.deb for control nodes with apt
  ansible.builtin.apt:
    pkg:
      - slurm-smd
      - slurm-smd-slurmctld
      - slurm-smd-client
  when: slurm_in_apt
