---
- name: Apt-get update
  ansible.builtin.apt:
    update_cache: true
- name: Install mariadb-server and mysql_config
  ansible.builtin.apt:
    pkg:
      - mariadb-server
      - default-libmysqlclient-dev

- name: Copy Slurm recommended mariaDB conf
  ansible.builtin.template:
    src: 60-slurm-custom.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-slurm-custom.cnf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Restart mariadb-server
  ansible.builtin.service:
    name: mariadb
    state: restarted
