---
- name: Copy mysql deb
  ansible.builtin.copy:
    src: mysql-apt-config_0.8.32-1_all.deb
    mode: '0644'
    dest: /tmp/mysql.deb
- name: Add mysql pkg
  ansible.builtin.apt:
    deb: /tmp/mysql.deb
- name: Apt-get update
  ansible.builtin.apt:
    update_cache: true
- name: Install mysql-server
  ansible.builtin.apt:
    pkg:
      - mysql-server
      - libmysqlclient-dev

- name: Set accounting for slurmdbd in mariadb-server
  ansible.builtin.shell: |
    mysql -e \"CREATE USER 'slurm'@'{{ slurm_db_host }}' identified by '{{ slurm_db_pass }}'\"
    mysql -e \"GRANT all ON slurm_acct_db.* TO 'slurm'@'{{ slurm_db_host }}' identified by '{{ slurm_db_pass }}' with grant option\"
    mysql -e \"create database slurm_acct_db;\"
  changed_when: true
