---
- name: prepare for DEB for all slurm nodes
  ansible.builtin.include_tasks: slurm.yml
  when: '"slurm_nodes" in group_names'

- name: install mariadb for db nodes
  ansible.builtin.include_tasks: db.yml
  when: '"hpc_db" in group_names'

- name: install slurm for slurmdbd nodes
  ansible.builtin.include_tasks: slurmdbd.yml
  when: '"hpc_slurmdbd" in group_names'

- name: install slurm for control nodes
  ansible.builtin.include_tasks: control.yml
  when: '"hpc_control" in group_names'

- name: install slurm for compute nodes
  ansible.builtin.include_tasks: compute.yml
  when: '"hpc_compute" in group_names'

- name: install slurm for login nodes
  ansible.builtin.include_tasks: login.yml
  when: '"hpc_login" in group_names'
