---
- name: Prepare for DEB for all slurm nodes
  ansible.builtin.include_tasks: slurm.yml
  when: '"slurm_nodes" in group_names'

- name: Set var for DB nodes list length
  ansible.builtin.set_fact:
    db_len: "{{ groups['hpc_db'] | length }}"
- name: Install mariadb for db nodes
  ansible.builtin.include_tasks: db.yml
  when: '"hpc_db" in group_names and db_len|int < 3'
- name: Install mariadb for db nodes with galera
  ansible.builtin.include_tasks: db_galera.yml
  when: '"hpc_db" in group_names and db_len|int >= 3 and groups["hpc_galera"][0] is defined'

- name: Install slurm for slurmdbd nodes
  ansible.builtin.include_tasks: slurmdbd.yml
  when: '"hpc_slurmdbd" in group_names'

- name: Install slurm for control nodes
  ansible.builtin.include_tasks: control.yml
  when: '"hpc_control" in group_names'

- name: Install slurm for compute nodes
  ansible.builtin.include_tasks: compute.yml
  when: '"hpc_compute" in group_names'

- name: Install slurm for login nodes
  ansible.builtin.include_tasks: login.yml
  when: '"hpc_login" in group_names'
