---
- name: Install slurm.deb for slurmdbd nodes
  ansible.builtin.apt:
    deb: /tmp/{{ item }}
  with_items:
    - slurm-smd_{{ slurm_install_version }}-1_amd64.deb
    - slurm-smd-slurmdbd_{{ slurm_install_version }}-1_amd64.deb
