---
- name: Add munge group
  ansible.builtin.group:
    name: munge
    gid: 150
    state: present
- name: Add munge user
  ansible.builtin.user:
    name: munge
    comment: "MUNGE Uid 'N' Gid Emporium"
    uid: 150
    group: munge
    shell: /usr/sbin/nologin
    createhome: false
    state: present

- name: Chown for /etc/munge
  ansible.builtin.file:
    path: /etc/munge
    owner: munge
    group: munge
    state: directory
    mode: '0700'

- name: Apt install munge & sudo
  ansible.builtin.apt:
    pkg:
      - libmunge-dev
      - libmunge2
      - munge
      - sudo
