---
- name: add munge group
  group:
    name: munge
    gid: 150
    state: present
- name: add munge user
  user:
    name: munge
    comment: "MUNGE Uid 'N' Gid Emporium"
    uid: 150
    group: munge
    shell: /usr/sbin/nologin
    createhome: no
    state: present

- name: chown for /etc/munge
  file:
    path: /etc/munge
    owner: munge
    group: munge
    state: directory
    mode: 0700

# - name: apt update
#   apt:
#     state: latest
#     name: "*"
#     update_cache: yes
- name: apt install munge & sudo
  apt:
    pkg:
      - libmunge-dev
      - libmunge2
      - munge
      - sudo
