---
- name: Create munge key
  ansible.builtin.command:
    cmd: sudo -u munge /usr/sbin/mungekey --verbose
    creates: /etc/munge/munge.key
  when: 'inventory_hostname == groups["hpc_control"][0]'

- name: Fetch munge key to local
  ansible.builtin.fetch:
    src: /etc/munge/munge.key
    dest: /tmp/munge.key
    flat: true
  when: 'not shared_munge and inventory_hostname == groups["hpc_control"][0]'
