---
- name: get ansible fact for hostname
  setup:
    filter:
      - 'ansible_hostname'

- name: create munge key
  shell: 
    cmd: sudo -u munge /usr/sbin/mungekey --verbose
    creates: /etc/munge/munge.key
  when: ansible_hostname == vars['munge_master']

- name: fetch munge key to local
  fetch:
    src: /etc/munge/munge.key
    dest: /tmp/munge.key
    flat: yes
  when: "ansible_hostname == vars['munge_master'] and not shared_munge"

- name: copy munge key to others
  copy:
    src: /tmp/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  when: '"slurm_nodes" in group_names and not shared_munge'

- name: enable and start munge service
  service:
    name: munge
    enabled: true
    state: started
