---
- name: create munge key
  become: yes
  become_user: munge
  shell: /usr/sbin/mungekey --verbose
  when: ansible_hostname == vars['munge_master']
- name: fetch munge key to local
  fetch:
    src: /etc/munge/munge.key
    dest: /tmp/munge.key
    flat: yes
  when: ansible_hostname == vars['munge_master']
- name: copy munge key to others
  copy:
    src: /tmp/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  when: '"slurm_nodes" in group_names'