---
- name: Install NFS client package
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Mount home directory and set in fstab
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/home"
    path: /home
    fstype: nfs
    state: mounted
  when: nfs_shared_home

- name: Set var for control nodes list length
  ansible.builtin.set_fact:
    ctrl_len: "{{ groups['hpc_control'] | length }}"
- name: Mount StateSaveLocation directory and set in fstab
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/share/slurm_state"
    path: /share/slurm_state
    fstype: nfs
    state: mounted
  when: >
    'ctrl_len|int > 1 and
    "hpc_control" in group_names and
    "hpc_storage" not in group_names'

- name: Mount slurm when shared_slurm_config
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/slurm"
    path: /etc/slurm
    fstype: nfs
    state: mounted
  when: shared_slurm_config

- name: Mount munge when shared_munge
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/munge"
    path: /etc/munge
    fstype: nfs
    state: mounted
  when: shared_munge

- name: Run systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
