---
- name: Install NFS client package
  apt:
    name: nfs-common
    state: latest

- name: Mount home directory and set in fstab
  mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/home"
    path: /home
    fstype: nfs
    state: mounted
  when: shared_home

- name: Mount /opt/spack directory and set in fstab
  mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/opt/spack"
    path: /opt/spack
    fstype: nfs
    state: mounted

- name: set var for control nodes list length
  set_fact:
    ctrl_len: "{{groups['hpc_control']|length}}"
- name: Mount StateSaveLocation directory and set in fstab
  mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/share/slurm_state"
    path: /share/slurm_state
    fstype: nfs
    state: mounted
  when: >
    'ctrl_len|int > 1 and
    "hpc_control" in group_names and 
    "hpc_storage" not in group_names'

- name: mount slurm when shared_config
  mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/slurm"
    path: /etc/slurm
    fstype: nfs
    state: mounted
  when: shared_config

- name: mount munge when shared_munge
  mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}/munge"
    path: /etc/munge
    fstype: nfs
    state: mounted
  when: shared_munge
