---
- name: Mount NFS
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ nfs_prefix }}"
    path: "/mnt/hpc"
    fstype: nfs
    state: ephemeral

- name: Create slurm when shared_slurm_config
  ansible.builtin.file:
    path: /mnt/hpc/slurm
    mode: '0755'
    state: directory
  when: shared_slurm_config
- name: Create munge when shared_munge
  ansible.builtin.file:
    path: /mnt/hpc/munge
    mode: '0700'
    state: directory
  when: shared_munge

- name: Set var for control nodes list length
  ansible.builtin.set_fact:
    ctrl_len: "{{ groups['hpc_control'] | length }}"
- name: Create StateSaveLocation
  ansible.builtin.file:
    path: /mnt/hpc/share/slurm_state
    mode: '0700'
    state: directory
  when: "ctrl_len|int > 1"

- name: Create home when nfs_shared_home
  ansible.builtin.file:
    path: /mnt/hpc/home
    mode: '0755'
    state: directory
  when: nfs_shared_home

- name: Unmount NFS
  ansible.posix.mount:
    path: "/mnt/hpc"
    state: unmounted
