---
- name: Install NFS kernel package
  apt:
    name: nfs-kernel-server
    state: latest

- name: copy home directories for NFS
  copy: 
    src: /home/
    dest: "{{ nfs_prefix }}/home"
    remote_src: true
    mode: preserve
  when: shared_home
- name: Setting up NFS server for /home
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ nfs_prefix }}/home {{ nfs_subnet }}(rw,sync,no_root_squash,no_subtree_check)"
    create: yes
  when: shared_home

- name: create /opt/spack directories for NFS
  file: 
    path: "{{ nfs_prefix }}/opt/spack"
    state: directory
- name: Setting up NFS server for /opt/spack
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_prefix }}/opt/spack {{ nfs_subnet }}(rw,sync,no_root_squash,no_subtree_check)"
    create: yes

- name: set var for control nodes list length
  set_fact:
    ctrl_len: "{{groups['hpc_control']|length}}"
- name: create StateSaveLocation directories for NFS
  file: 
    path: "{{ nfs_prefix }}/share/slurm_state"
    state: directory
  when: "ctrl_len|int > 1"
- name: Setting up NFS server for StateSaveLocation
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ nfs_prefix }}/share/slurm_state {{ nfs_subnet }}(rw,sync,no_root_squash,no_subtree_check)"
    create: yes
  when: "ctrl_len|int > 1"

- name: create StateSaveLocation for both control node and storage
  file:
    path: /share
    state: directory
  when: >
    'ctrl_len|int > 1 and
    "hpc_control" in group_names and 
    "hpc_storage" in group_names'
- name: Setting up StateSaveLocation for both control node and storage
  file:
    src: "{{ nfs_prefix }}/share/slurm_state"
    dest: /share/slurm_state
    state: link
  when: >
    'ctrl_len|int > 1 and
    "hpc_control" in group_names and 
    "hpc_storage" in group_names'

- name: create slurm directory for NFS
  file: 
    path: "{{ nfs_prefix }}/slurm"
    owner: 151
    group: 151
    mode: 0755
    state: directory
  when: shared_config
- name: Setting up NFS server for slurm
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_prefix }}/slurm {{ nfs_subnet }}(rw,sync,no_root_squash,no_subtree_check)"
    create: yes
  when: shared_config

- name: create munge directory for NFS
  file:
    path: "{{ nfs_prefix }}/munge"
    owner: 150
    group: 150
    mode: 0700
    state: directory
  when: shared_munge
- name: Setting up NFS server for munge
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_prefix }}/munge {{ nfs_subnet }}(rw,sync,no_root_squash,no_subtree_check)"
    create: yes
  when: shared_munge

- name: Setting up slurm for both control node and storage
  file:
    src: "{{ nfs_prefix }}/slurm"
    dest: /etc/slurm
    state: link
  when: >
    'shared_config and
    "hpc_control" in group_names and 
    "hpc_storage" in group_names'
- name: Setting up munge for both control node and storage
  file:
    src: "{{ nfs_prefix }}/munge"
    dest: /etc/munge
    state: link
  when: >
    'shared_munge and
    "hpc_control" in group_names and 
    "hpc_storage" in group_names'

- name: Reload NFS
  command: exportfs -ra
