---
- name: Check nvidia driver
  ansible.builtin.command: nvidia-smi
  ignore_errors: true
  register: nvidia_driver
  changed_when: false
- name: Abort if nvidia driver is installed
  ansible.builtin.fail:
    msg: "NVIDIA driver is installed"
  when: nvidia_driver.rc == 0
- name: Check runfile
  ansible.builtin.stat:
    path: "/tmp/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run"
  register: runfile
- name: Get runfile
  ansible.builtin.get_url:
    url: https://developer.download.nvidia.com/compute/cuda/{{ cuda_version }}/local_installers/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run
    dest: /tmp/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run
    mode: '0755'
  when: not runfile.stat.exists
- name: Install with runfile
  ansible.builtin.command: "sh /tmp/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run --silent --driver --toolkit"
  register: install_cuda
  changed_when: install_cuda.rc == 0
