---
- name: check nvidia driver
  shell: nvidia-smi
  ignore_errors: true
  register: nvidia_driver
- name: abort if nvidia driver is installed
  fail:
    msg: "NVIDIA driver is installed"
  when: nvidia_driver.rc == 0
- name: check runfile
  stat:
    path: "/tmp/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run"
  register: runfile
- name: get runfile
  shell: "wget https://developer.download.nvidia.com/compute/cuda/{{ cuda_version }}/local_installers/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run -O /tmp/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run"
  when: not runfile.stat.exists
- name: install with runfile
  shell: "sh /tmp/cuda_{{ cuda_version }}_{{ nv_driver_version }}_linux.run --silent --driver --toolkit"
