---
- name: Get uname -r
  ansible.builtin.command: "uname -r"
  register: uname
  changed_when: false
- name: Install kernel header
  ansible.builtin.apt:
    name: "linux-headers-{{ uname.stdout }}"
    state: present
- name: Disable nouveau config
  ansible.builtin.command:
    cmd: |
      mkdir -p /etc/modprobe.d &&
      echo "blacklist nouveau" > /etc/modprobe.d/blacklist-nouveau.conf &&
      echo "options nouveau modeset=0" >> /etc/modprobe.d/blacklist-nouveau.conf
  register: nouveau
  changed_when: nouveau.rc == 0
- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  register: initramfs
  changed_when: initramfs.rc == 0
- name: Reboot
  ansible.builtin.reboot:
