---
- name: create necessary file for slurmd
  file:
    path: /var/log/slurmd.log
    state: touch
    owner: slurm
    group: slurm
- name: create necessary directory for slurmd
  file:
    path: /var/spool/slurmd
    state: directory
    owner: slurm
    group: slurm
- name: start slurmd (for compute)
  service:
    name: slurmd
    state: restarted
