---
- name: Create necessary file for slurmd
  ansible.builtin.file:
    path: /var/log/slurmd.log
    state: touch
    owner: slurm
    group: slurm
    mode: '0644'
- name: Create necessary directory for slurmd
  ansible.builtin.file:
    path: /var/spool/slurmd
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'
- name: Start slurmd (for compute)
  ansible.builtin.service:
    name: slurmd
    enabled: true
    state: restarted
