---
- name: Create necessary file for slurmctld
  ansible.builtin.file:
    path: /var/log/slurmctld.log
    state: touch
    owner: slurm
    group: slurm
    mode: '0644'
- name: Create necessary directory for slurmctld
  ansible.builtin.file:
    path: /var/spool/slurmctld
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Set StateSaveLocation correct permission
  ansible.builtin.file:
    path: /share/slurm_state
    state: directory
    owner: slurm
    group: slurm
    mode: '0700'
  when: "groups['hpc_control'][1] is defined"

- name: Restart slurmctld (for control)
  ansible.builtin.service:
    name: slurmctld
    enabled: true
    state: restarted

- name: Check if cluster has been added
  ansible.builtin.shell:
    cmd: |
      set -o pipefail &&
      sacctmgr -n show cluster format=cluster%{{ slurm_cluster_name | length }} | grep {{ slurm_cluster_name }}
  register: check_cluster
  ignore_errors: true
  changed_when: false
  when: 'inventory_hostname == groups["hpc_control"][0]'

- name: Make slurmctld able to reach slurmdbd
  ansible.builtin.command:
    cmd: sacctmgr -i add cluster {{ slurm_cluster_name }}
  register: add_cluster
  changed_when: add_cluster.rc == 0
  when: 'inventory_hostname == groups["hpc_control"][0] and check_cluster.rc != 0'
