---
- name: create necessary file for slurmctld
  file: 
    path: /var/log/slurmctld.log
    state: touch
    owner: slurm
    group: slurm
- name: create necessary directory for slurmctld
  file:
    path: /var/spool/slurmctld
    state: directory
    owner: slurm
    group: slurm
- name: restart slurmctld (for control)
  service:
    name: slurmctld
    state: restarted
