---
- name: Install dependency for mysql module
  ansible.builtin.apt:
    name: python3-mysqldb

- name: Prompt for slurm_db_pass
  ansible.builtin.pause:
    prompt: "Enter the DB password for slurm"
    echo: false
  register: input
- name: Set var for all hosts
  ansible.builtin.set_fact:
    slurm_db_pass: "{{ input.user_input }}"
  run_once: true

- name: Set accounting for DBD nodes in mariadb-server
  community.mysql.mysql_user:
    name: slurm
    password: "{{ slurm_db_pass }}"
    host: "{{ hostvars[item]['ansible_facts']['fqdn'] }}"
    priv: "slurm_acct_db.*:ALL,GRANT"
    state: present
  loop: "{{ groups['hpc_slurmdbd'] }}"

- name: Set accounting for localhost when mariadb-server in DBD
  community.mysql.mysql_user:
    name: slurm
    password: "{{ slurm_db_pass }}"
    host: localhost
    priv: "slurm_acct_db.*:ALL,GRANT"
    state: present
  when: "groups['hpc_db'][0] in groups['hpc_slurmdbd']"

- name: Create slurm_acct_db database
  community.mysql.mysql_db:
    name: slurm_acct_db
    state: present
