---
- name: Get ansible facts
  ansible.builtin.setup:
    filter:
      - 'ansible_fqdn'
      - 'ansible_hostname'

- name: Config for all slurm nodes
  ansible.builtin.include_tasks: slurm.yml
  when: '"slurm_nodes" in group_names'

- name: Config slurm for db node
  ansible.builtin.include_tasks: db.yml
  when: '"hpc_db" in group_names and inventory_hostname == groups["hpc_db"][0]'

- name: Config slurm for slurmdbd nodes
  ansible.builtin.include_tasks: slurmdbd.yml
  when: '"hpc_slurmdbd" in group_names'

- name: Config slurm for control nodes
  ansible.builtin.include_tasks: control.yml
  when: '"hpc_control" in group_names'

- name: Config slurm for compute nodes
  ansible.builtin.include_tasks: compute.yml
  when: '"hpc_compute" in group_names'
