---
- name: Create necessary file for slurmdbd
  ansible.builtin.file:
    path: /var/run/slurmdbd.pid
    state: touch
    owner: slurm
    group: slurm
    mode: '0644'
- name: Create log file for slurmdbd
  ansible.builtin.file:
    path: /var/log/slurmdbd.log
    state: touch
    owner: slurm
    group: slurm
    mode: '0644'

- name: Write slurmdbd.conf using jinja2 template to NFS
  ansible.builtin.template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: '0600'
  when: 'shared_slurm_config and inventory_hostname == groups["hpc_slurmdbd"][0]'
- name: Write slurmdbd.conf using jinja2 template to all slurmdbd
  ansible.builtin.template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: '0600'
  when: 'not shared_slurm_config'

- name: Start slurmdbd
  ansible.builtin.service:
    name: slurmdbd
    enabled: true
    state: restarted
