---
- name: create necessary file for slurmdbd
  file: 
    path: /var/run/slurmdbd.pid
    state: touch
    owner: slurm
    group: slurm
- name: create log file for slurmdbd
  file:
    path: /var/log/slurmdbd.log
    state: touch
    owner: slurm
    group: slurm

- name: write slurmdbd.conf using jinja2 template to NFS
  template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: '0600'
  when: 'shared_config and inventory_hostname == groups["hpc_slurmdbd"][0]'
- name: write slurmdbd.conf using jinja2 template to all slurmdbd
  template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: '0600'
  when: 'not shared_config'

- name: start slurmdbd
  service:
    name: slurmdbd
    enabled: true
    state: restarted
