---
- name: Write slurm.conf using jinja2 template for all nodes
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: slurm
    mode: '0644'
  when: 'not shared_config'

- name: 1st ctrl node write slurm.conf using jinja2 template to NFS
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: slurm
    mode: '0644'
  when: 'shared_config and inventory_hostname == groups["hpc_control"][0]'
