---
- name: make all slurm packages absent
# if the package is not installed, ansible will answer okay
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: yes
  with_items:
    "{{ slurm_packages }}"
  when: "'slurm_nodes' in group_names"
 