---
- name: Make all slurm packages absent
# if the package is not installed, ansible will answer okay
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    autoremove: true
  with_items:
    "{{ slurm_remove_packages }}"
  when: "'slurm_nodes' in group_names"
